#!/usr/bin/env python3
"""
YouTopia — ytmusicapi HTTP sidecar.

Exposes a tiny FastAPI/http.server JSON API on localhost so the TypeScript
server can reach YTM catalog, search, and playlist data without any Node.js
ytmusicapi binding.

Endpoints (all GET unless noted):
  GET  /health                      — liveness + auth status
  GET  /search?q=<text>&limit=<n>   — search tracks/albums/artists
  GET  /track/<videoId>             — track metadata
  GET  /album/<browseId>            — album metadata + track list
  GET  /artist/<channelId>          — artist metadata + albums
  GET  /playlist/<playlistId>       — playlist metadata + tracks
  GET  /library/songs?limit=<n>     — liked/library songs (requires auth)
  GET  /library/albums?limit=<n>    — library albums
  GET  /library/playlists           — library playlists

Auth:
  ytmusicapi can operate in two modes:
    1. Browser cookie auth: set YTMUSIC_AUTH_FILE env to a JSON headers file
       generated by `ytmusicapi browser` or `ytmusicapi oauth`.
    2. Unauthenticated: limited to public search/catalog (no library, no
       private playlists, 128 kbps only from yt-dlp unless cookies provided).

Run:
  pip install -r requirements.txt
  YTMUSIC_AUTH_FILE=/path/to/headers.json python3 sidecar.py

Or from the TypeScript server (supervised child process) via:
  YTMUSIC_PORT=9871 python3 server/sidecars/ytmusic/sidecar.py
"""

from __future__ import annotations

import json
import logging
import os
import sys
import traceback
from http.server import BaseHTTPRequestHandler, HTTPServer
from urllib.parse import urlparse, parse_qs
from typing import Any

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [ytmusic-sidecar] %(levelname)s %(message)s",
    stream=sys.stderr,
)
log = logging.getLogger("ytmusic-sidecar")

# ---------------------------------------------------------------------------
# ytmusicapi init
# ---------------------------------------------------------------------------

try:
    from ytmusicapi import YTMusic  # type: ignore[import]
    YTMUSICAPI_AVAILABLE = True
except ImportError:
    YTMUSICAPI_AVAILABLE = False
    log.warning("ytmusicapi not installed — sidecar will report not-ready. "
                "Run: pip install -r server/sidecars/ytmusic/requirements.txt")

yt: Any = None  # YTMusic instance


def init_ytmusic() -> None:
    """Initialize the YTMusic client (authenticated if auth file present)."""
    global yt
    if not YTMUSICAPI_AVAILABLE:
        return

    auth_file = os.environ.get("YTMUSIC_AUTH_FILE", "")
    try:
        if auth_file and os.path.exists(auth_file):
            yt = YTMusic(auth_file)
            log.info("YTMusic initialized with auth from %s", auth_file)
        else:
            yt = YTMusic()
            log.info("YTMusic initialized (unauthenticated — limited catalog)")
    except Exception as exc:  # noqa: BLE001
        log.error("Failed to initialize YTMusic: %s", exc)
        yt = None


# ---------------------------------------------------------------------------
# Response helpers
# ---------------------------------------------------------------------------

def ok(data: Any) -> bytes:
    return json.dumps({"ok": True, "data": data}, default=str).encode()


def err(msg: str, code: int = 500) -> tuple[int, bytes]:
    return code, json.dumps({"ok": False, "error": msg}).encode()


# ---------------------------------------------------------------------------
# Normalisation helpers — map YTM shapes to YouTopia Track/Album/Artist shapes
# ---------------------------------------------------------------------------

def _artwork(thumbnails: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Sort thumbnails largest-first (YTM usually puts smallest first)."""
    return sorted(thumbnails or [], key=lambda t: t.get("width", 0) or 0, reverse=True)


def normalise_track(item: dict[str, Any], video_id: str | None = None) -> dict[str, Any]:
    vid = video_id or item.get("videoId", "")
    artists = item.get("artists") or []
    artist_name = ", ".join(a.get("name", "") for a in artists) or "Unknown Artist"
    artist_ids = [a.get("id", "") for a in artists if a.get("id")]

    album = item.get("album") or {}
    thumbnails = item.get("thumbnails") or []

    duration_seconds = 0
    dur = item.get("duration") or item.get("duration_seconds")
    if isinstance(dur, (int, float)):
        duration_seconds = float(dur)
    elif isinstance(dur, str):
        # "3:45" format
        parts = dur.split(":")
        try:
            if len(parts) == 2:  # noqa: PLR2004
                duration_seconds = int(parts[0]) * 60 + int(parts[1])
            elif len(parts) == 3:  # noqa: PLR2004
                duration_seconds = int(parts[0]) * 3600 + int(parts[1]) * 60 + int(parts[2])
        except ValueError:
            pass

    return {
        "kind": "track",
        "nativeId": vid,
        "id": f"ytmusic:track:{vid}",
        "source": "ytmusic",
        "title": item.get("title", "Unknown Track"),
        "artwork": _artwork(thumbnails),
        "artistName": artist_name,
        "artistIds": [f"ytmusic:artist:{aid}" for aid in artist_ids],
        "albumName": album.get("name") or None,
        "albumId": f"ytmusic:album:{album['id']}" if album.get("id") else None,
        "durationSeconds": duration_seconds,
        "explicit": item.get("isExplicit", False),
        "hasVideo": item.get("videoType") == "MUSIC_VIDEO_TYPE_MV",
        "isrc": item.get("isrc"),
    }


def normalise_album(item: dict[str, Any]) -> dict[str, Any]:
    artists = item.get("artists") or []
    artist_name = ", ".join(a.get("name", "") for a in artists) or "Unknown Artist"
    artist_ids = [a.get("id", "") for a in artists if a.get("id")]
    thumbnails = item.get("thumbnails") or []
    browse_id = item.get("browseId") or item.get("audioPlaylistId") or ""
    return {
        "kind": "album",
        "nativeId": browse_id,
        "id": f"ytmusic:album:{browse_id}",
        "source": "ytmusic",
        "title": item.get("title", "Unknown Album"),
        "artwork": _artwork(thumbnails),
        "artistName": artist_name,
        "artistIds": [f"ytmusic:artist:{aid}" for aid in artist_ids],
        "year": item.get("year"),
        "trackCount": item.get("trackCount"),
    }


def normalise_artist(item: dict[str, Any]) -> dict[str, Any]:
    thumbnails = item.get("thumbnails") or []
    channel_id = item.get("browseId") or item.get("id") or ""
    return {
        "kind": "artist",
        "nativeId": channel_id,
        "id": f"ytmusic:artist:{channel_id}",
        "source": "ytmusic",
        "title": item.get("artist") or item.get("name") or "Unknown Artist",
        "artwork": _artwork(thumbnails),
        "description": item.get("description"),
        "genres": item.get("genres"),
    }


def normalise_playlist(item: dict[str, Any]) -> dict[str, Any]:
    thumbnails = item.get("thumbnails") or []
    pid = item.get("playlistId") or item.get("id") or ""
    return {
        "kind": "playlist",
        "nativeId": pid,
        "id": f"ytmusic:playlist:{pid}",
        "source": "ytmusic",
        "title": item.get("title", "Unknown Playlist"),
        "artwork": _artwork(thumbnails),
        "description": item.get("description"),
        "ownerName": item.get("author"),
        "trackCount": item.get("count"),
    }


# ---------------------------------------------------------------------------
# Request handlers
# ---------------------------------------------------------------------------

def handle_health() -> dict[str, Any]:
    return {
        "ready": yt is not None,
        "ytmusicapiAvailable": YTMUSICAPI_AVAILABLE,
        "authenticated": bool(os.environ.get("YTMUSIC_AUTH_FILE")),
        "message": (
            "Ready" if yt is not None
            else ("ytmusicapi not installed" if not YTMUSICAPI_AVAILABLE else "init failed")
        ),
    }


def handle_search(params: dict[str, list[str]]) -> dict[str, Any]:
    if yt is None:
        return {"tracks": [], "albums": [], "artists": [], "playlists": [], "error": "not-ready"}

    q = (params.get("q") or [""])[0]
    limit_str = (params.get("limit") or ["25"])[0]
    limit = min(int(limit_str), 100)

    raw = yt.search(q, limit=limit)

    tracks = []
    albums = []
    artists = []
    playlists = []

    for item in raw:
        rtype = item.get("resultType", "")
        if rtype == "song" or rtype == "video":
            tracks.append(normalise_track(item))
        elif rtype == "album":
            albums.append(normalise_album(item))
        elif rtype == "artist":
            artists.append(normalise_artist(item))
        elif rtype == "playlist":
            playlists.append(normalise_playlist(item))

    return {"tracks": tracks, "albums": albums, "artists": artists, "playlists": playlists}


def handle_track(video_id: str) -> dict[str, Any]:
    if yt is None:
        raise RuntimeError("not-ready")
    item = yt.get_song(video_id)
    video_details = item.get("videoDetails") or {}
    thumbnails = video_details.get("thumbnail", {}).get("thumbnails") or []
    duration_seconds = float(video_details.get("lengthSeconds") or 0)
    return {
        "kind": "track",
        "nativeId": video_id,
        "id": f"ytmusic:track:{video_id}",
        "source": "ytmusic",
        "title": video_details.get("title", "Unknown Track"),
        "artwork": _artwork(thumbnails),
        "artistName": video_details.get("author") or "Unknown Artist",
        "artistIds": [],
        "albumName": None,
        "albumId": None,
        "durationSeconds": duration_seconds,
        "explicit": False,
        "hasVideo": False,
        "isrc": None,
    }


def handle_album(browse_id: str) -> dict[str, Any]:
    if yt is None:
        raise RuntimeError("not-ready")
    item = yt.get_album(browse_id)
    album = normalise_album({**item, "browseId": browse_id})
    raw_tracks = item.get("tracks") or []
    tracks = [normalise_track(t) for t in raw_tracks]
    return {"album": album, "tracks": tracks}


def handle_artist(channel_id: str) -> dict[str, Any]:
    if yt is None:
        raise RuntimeError("not-ready")
    item = yt.get_artist(channel_id)
    artist = normalise_artist({**item, "browseId": channel_id})
    albums_raw = (item.get("albums") or {}).get("results") or []
    albums = [normalise_album(a) for a in albums_raw]
    return {"artist": artist, "albums": albums}


def handle_playlist(playlist_id: str) -> dict[str, Any]:
    if yt is None:
        raise RuntimeError("not-ready")
    item = yt.get_playlist(playlist_id)
    playlist = normalise_playlist({**item, "playlistId": playlist_id})
    raw_tracks = item.get("tracks") or []
    tracks = [normalise_track(t) for t in raw_tracks]
    return {"playlist": playlist, "tracks": tracks}


def handle_library_songs(params: dict[str, list[str]]) -> list[dict[str, Any]]:
    if yt is None:
        raise RuntimeError("not-ready")
    limit_str = (params.get("limit") or ["100"])[0]
    limit = min(int(limit_str), 500)
    raw = yt.get_library_songs(limit=limit)
    return [normalise_track(t) for t in raw]


def handle_library_albums(params: dict[str, list[str]]) -> list[dict[str, Any]]:
    if yt is None:
        raise RuntimeError("not-ready")
    limit_str = (params.get("limit") or ["100"])[0]
    limit = min(int(limit_str), 500)
    raw = yt.get_library_albums(limit=limit)
    return [normalise_album(a) for a in raw]


def handle_library_playlists() -> list[dict[str, Any]]:
    if yt is None:
        raise RuntimeError("not-ready")
    raw = yt.get_library_playlists()
    return [normalise_playlist(p) for p in raw]


# ---------------------------------------------------------------------------
# HTTP handler
# ---------------------------------------------------------------------------

class SidecarHandler(BaseHTTPRequestHandler):
    def log_message(self, fmt: str, *args: Any) -> None:  # noqa: ANN002
        log.debug(fmt, *args)

    def send_json(self, data: bytes, code: int = 200) -> None:
        self.send_response(code)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(data)))
        self.end_headers()
        self.wfile.write(data)

    def do_GET(self) -> None:  # noqa: N802
        parsed = urlparse(self.path)
        params = parse_qs(parsed.query)
        route = parsed.path.rstrip("/")

        try:
            if route == "/health":
                self.send_json(ok(handle_health()))

            elif route == "/search":
                self.send_json(ok(handle_search(params)))

            elif route.startswith("/track/"):
                vid = route[len("/track/"):]
                self.send_json(ok(handle_track(vid)))

            elif route.startswith("/album/"):
                bid = route[len("/album/"):]
                self.send_json(ok(handle_album(bid)))

            elif route.startswith("/artist/"):
                cid = route[len("/artist/"):]
                self.send_json(ok(handle_artist(cid)))

            elif route.startswith("/playlist/"):
                pid = route[len("/playlist/"):]
                self.send_json(ok(handle_playlist(pid)))

            elif route == "/library/songs":
                self.send_json(ok(handle_library_songs(params)))

            elif route == "/library/albums":
                self.send_json(ok(handle_library_albums(params)))

            elif route == "/library/playlists":
                self.send_json(ok(handle_library_playlists()))

            else:
                code, body = err(f"Not found: {route}", 404)
                self.send_json(body, code)

        except Exception as exc:  # noqa: BLE001
            log.error("Request error: %s\n%s", exc, traceback.format_exc())
            code, body = err(str(exc), 500)
            self.send_json(body, code)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    init_ytmusic()
    port = int(os.environ.get("YTMUSIC_PORT", "9871"))
    host = os.environ.get("YTMUSIC_HOST", "127.0.0.1")
    server = HTTPServer((host, port), SidecarHandler)
    log.info("ytmusic-sidecar listening on http://%s:%d", host, port)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        log.info("Shutting down")
        server.server_close()


if __name__ == "__main__":
    main()
